import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <footer className="p-4 bg-black text-white text-neutral-content grid grid-cols-[1fr_1fr]">
          <div>
            <span>© 2025 CoreNion</span>
            <br />
            <Link className="underline text-white mr-2" href="/privacy" target="_blank">Privacy</Link>
            <Link className="underline text-blue-200" href="https://github.com/CoreNion/page" target="_blank">Source Code</Link>
          </div>

          <nav className="grid grid-cols-[repeat(3,auto)] justify-end items-center gap-4">
            <Link href="https://github.com/CoreNion">
              <Icon icon="carbon:logo-github" height="40px"></Icon>
            </Link>
            <Link href="https://x.com/CoreiNion">
              <Icon icon="carbon:logo-x" height="40px"></Icon>
            </Link>

            <button className="bg-yellow-100 text-black rounded-full p-2">
              <Icon icon="carbon:data-analytics" height="25px"></Icon>
            </button>
          </nav>
        </footer>
      </body>
    </html>
  );
}
